#----------------------------------- ALARMA ORIGINAL:  the  ---------------------------#
Tipo de alarma: NOTIFICATION-TYPE
Nombre de alarma: the
"The object identifier from the NOTIFICATION-TYPE for the
notification to use if metEventActions has 'notification' set."
DEFVAL { zeroDotZero }
::= { mteEventNotificationEntry 1 }
#----------------------------------- FIN ALARMA ORIGINAL ---------------------------#
#----------------------------------- ALARMA ORIGINAL:  mteTriggerFired  ---------------------------#
Tipo de alarma: NOTIFICATION-TYPE
Nombre de alarma: mteTriggerFired
mteTriggerFired NOTIFICATION-TYPE
OBJECTS { mteHotTrigger,
mteHotTargetName,
mteHotContextName,
mteHotOID,
mteHotValue }
STATUS  current
DESCRIPTION
"Notification that the trigger indicated by the object
instances has fired, for triggers with mteTriggerType
'boolean' or 'existence'."
::= { dismanEventMIBNotifications 1 }
#----------------------------------- FIN ALARMA ORIGINAL ---------------------------#
#----------------------------------- ALARMA ORIGINAL:  mteTriggerRising  ---------------------------#
Tipo de alarma: NOTIFICATION-TYPE
Nombre de alarma: mteTriggerRising
mteTriggerRising NOTIFICATION-TYPE
OBJECTS { mteHotTrigger,
mteHotTargetName,
mteHotContextName,
mteHotOID,
mteHotValue }
STATUS  current
DESCRIPTION
"Notification that the rising threshold was met for triggers
with mteTriggerType 'threshold'."
::= { dismanEventMIBNotifications 2 }
#----------------------------------- FIN ALARMA ORIGINAL ---------------------------#
#----------------------------------- ALARMA ORIGINAL:  mteTriggerFalling  ---------------------------#
Tipo de alarma: NOTIFICATION-TYPE
Nombre de alarma: mteTriggerFalling
mteTriggerFalling NOTIFICATION-TYPE
OBJECTS { mteHotTrigger,
mteHotTargetName,
mteHotContextName,
mteHotOID,
mteHotValue }
STATUS  current
DESCRIPTION
"Notification that the falling threshold was met for triggers
with mteTriggerType 'threshold'."
::= { dismanEventMIBNotifications 3 }
#----------------------------------- FIN ALARMA ORIGINAL ---------------------------#
#----------------------------------- ALARMA ORIGINAL:  mteTriggerFailure  ---------------------------#
Tipo de alarma: NOTIFICATION-TYPE
Nombre de alarma: mteTriggerFailure
mteTriggerFailure NOTIFICATION-TYPE
OBJECTS { mteHotTrigger,
mteHotTargetName,
mteHotContextName,
mteHotOID,
mteFailedReason }
STATUS  current
DESCRIPTION
"Notification that an attempt to check a trigger has failed.
The network manager must enable this notification only with
a certain fear and trembling, as it can easily crowd out more
important information.  It should be used only to help diagnose
a problem that has appeared in the error counters and can not
be found otherwise."
::= { dismanEventMIBNotifications 4 }
#----------------------------------- FIN ALARMA ORIGINAL ---------------------------#
#----------------------------------- ALARMA ORIGINAL:  mteEventSetFailure  ---------------------------#
Tipo de alarma: NOTIFICATION-TYPE
Nombre de alarma: mteEventSetFailure
mteEventSetFailure NOTIFICATION-TYPE
OBJECTS { mteHotTrigger,
mteHotTargetName,
mteHotContextName,
mteHotOID,
mteFailedReason }
STATUS  current
DESCRIPTION
"Notification that an attempt to do a set in response to an
event has failed.
The network manager must enable this notification only with
a certain fear and trembling, as it can easily crowd out more
important information.  It should be used only to help diagnose
a problem that has appeared in the error counters and can not
be found otherwise."
::= { dismanEventMIBNotifications 5 }
#----------------------------------- FIN ALARMA ORIGINAL ---------------------------#
----------------------------------- mteEventSetFailure ---------------------------
mteEventSetFailure:
  TYPE: NOTIFICATION-TYPE
  OBJECTS: mteHotTrigger, mteHotTargetName, mteHotContextName, mteHotOID, mteFailedReason 
  STATUS: current
  DESCRIPTION: Notification that an attempt to do a set in response to an event has failed. The network manager must enable this notification only with a certain fear and trembling, as it can easily crowd out more important information.  It should be used only to help diagnose a problem that has appeared in the error counters and can not be found otherwise.
  OID: dismanEventMIBNotifications 5
  VARIABLES: No se encontraron variables
  ENTERPRISE: No se encontró la empresa
----------------------------------- Final de segmento -----------------------------------
----------------------------------- mteTriggerRising ---------------------------
mteTriggerRising:
  TYPE: NOTIFICATION-TYPE
  OBJECTS: mteHotTrigger, mteHotTargetName, mteHotContextName, mteHotOID, mteHotValue 
  STATUS: current
  DESCRIPTION: Notification that the rising threshold was met for triggers with mteTriggerType 'threshold'.
  OID: dismanEventMIBNotifications 2
  VARIABLES: No se encontraron variables
  ENTERPRISE: No se encontró la empresa
----------------------------------- Final de segmento -----------------------------------
----------------------------------- mteTriggerFalling ---------------------------
mteTriggerFalling:
  TYPE: NOTIFICATION-TYPE
  OBJECTS: mteHotTrigger, mteHotTargetName, mteHotContextName, mteHotOID, mteHotValue 
  STATUS: current
  DESCRIPTION: Notification that the falling threshold was met for triggers with mteTriggerType 'threshold'.
  OID: dismanEventMIBNotifications 3
  VARIABLES: No se encontraron variables
  ENTERPRISE: No se encontró la empresa
----------------------------------- Final de segmento -----------------------------------
----------------------------------- mteTriggerFailure ---------------------------
mteTriggerFailure:
  TYPE: NOTIFICATION-TYPE
  OBJECTS: mteHotTrigger, mteHotTargetName, mteHotContextName, mteHotOID, mteFailedReason 
  STATUS: current
  DESCRIPTION: Notification that an attempt to check a trigger has failed. The network manager must enable this notification only with a certain fear and trembling, as it can easily crowd out more important information.  It should be used only to help diagnose a problem that has appeared in the error counters and can not be found otherwise.
  OID: dismanEventMIBNotifications 4
  VARIABLES: No se encontraron variables
  ENTERPRISE: No se encontró la empresa
----------------------------------- Final de segmento -----------------------------------
----------------------------------- the ---------------------------
the:
  TYPE: NOTIFICATION-TYPE
  OBJECTS: No se encontraron objetos
  STATUS: No se encontró el estado
  DESCRIPTION: No se encontró la descripción
  OID: mteEventNotificationEntry 1
  VARIABLES: No se encontraron variables
  ENTERPRISE: No se encontró la empresa
----------------------------------- Final de segmento -----------------------------------
----------------------------------- mteTriggerFired ---------------------------
mteTriggerFired:
  TYPE: NOTIFICATION-TYPE
  OBJECTS: mteHotTrigger, mteHotTargetName, mteHotContextName, mteHotOID, mteHotValue 
  STATUS: current
  DESCRIPTION: Notification that the trigger indicated by the object instances has fired, for triggers with mteTriggerType 'boolean' or 'existence'.
  OID: dismanEventMIBNotifications 1
  VARIABLES: No se encontraron variables
  ENTERPRISE: No se encontró la empresa
----------------------------------- Final de segmento -----------------------------------
